---
- name:             Check whether hostname exists in /etc/dehydrated/domains.txt
  command:          grep -E "^{{ hostname }}" /etc/dehydrated/domains.txt
  check_mode:       no
  ignore_errors:    yes
  changed_when:     no
  register:         hostname_exists

- name: Add hostname to Dehydrated
  lineinfile:
    path: /etc/dehydrated/domains.txt
    regexp: "^{{ hostname }}"
    line: "{{ hostname }}"
  when: hostname_exists.rc != 0

- name: Run Dehydrated
  command: "/usr/sbin/dehydrated -c -g -k /etc/letsencrypt/hooks.sh --domain {{ hostname }}"
  when: hostname_exists.rc != 0
