---
- name: Create root directory
  file:
    path: "/var/www/{{ hostname }}"
    state: directory
    mode: '0750'
    owner: root
    group: www-data

- name: Create subdirectories
  file:
    path: "/var/www/{{ hostname }}{{ item }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  with_items:
    - /.ssh
    - /etc
    - /run
    - /logs
    - /wwwroot
  loop_control:
    label: "/var/www/{{ hostname }}{{ item }}"

- name: Create user
  user:
    name: "{{ hostname | replace('.','_') }}"
    uid: 33
    group: www-data
    non_unique: yes
    home: "/var/www/{{ hostname }}"
    shell: /bin/bash

- name: Create Apache2 configuration
  template:
    src: apache2.conf
    dest: /etc/apache2/sites-available/{{ hostname }}.conf
    owner: root
    group: root
    mode: '0644'
    force: no
  notify: restart apache2

- name: Enable Apache2 configuration
  file:
    src: /etc/apache2/sites-available/{{ hostname }}.conf
    dest: /etc/apache2/sites-enabled/{{ hostname }}.conf
    owner: root
    group: root
    state: link
  notify: restart apache2

- name: Create PHP-FPM configuration
  template:
    src: php-fpm.conf
    dest: /var/www/{{ hostname }}/etc/php-fpm.conf
    owner: root
    group: root
    mode: '0644'

- name: Create local configuration files
  copy:
    content: ""
    dest: "/var/www/{{ hostname }}/etc/php-fpm.local"
    force: no

- name: Start Docker container for PHP-FPM
  docker_container:
    name: "{{ hostname }}"
    image: "intux/php:{{ php }}"
    user: www-data
    command: ["/usr/sbin/php-fpm{{ php }}", "-F", "-y", "/var/www/{{ hostname }}/etc/php-fpm.conf"]
    network_mode: host
    pull: yes
    restart_policy: always
    volumes:
      - "/var/www/{{ hostname }}:/var/www/{{ hostname }}"

- include: "letsencrypt.yml"
  when: letsencrypt


